export const USER_ADMIN_DRAWER_TEXTS = {
  SECTIONS: {
    PERSONAL_DATA: 'Dados Pessoais',
    PHONES: 'Telefones',
    ADDRESSES: 'Endereços',
    ACCESS_STATUS: 'Acesso e Status',
    ADMIN_ACTIONS: 'Ações Administrativas',
  },
  LABELS: {
    UPLOAD: 'Upload',
    FIRST_NAME: 'Nome',
    LAST_NAME: 'Sobrenome',
    CPF: 'CPF',
    BIRTH_DATE: 'Data de Nascimento',
    EMAIL: 'E-mail',
    PHONE: (index: number) => `Telefone ${index + 1}`,
    IS_WHATSAPP: 'É WhatsApp?',
    IS_PRIMARY_PHONE: 'Principal',
    ZIP_CODE: 'CEP',
    CITY: 'Cidade',
    STREET: 'Rua',
    NUMBER: 'Número',
    NEIGHBORHOOD: 'Bairro',
    COMPLEMENT: 'Complemento',
    STATE: 'Estado (UF)',
    IS_PRIMARY_ADDRESS: 'Endereço Principal',
    ROLE: 'Nível (Role)',
    STATUS: 'Status',
    PASSWORD: 'Senha',
    PASSWORD_PLACEHOLDER_EDIT: 'Deixe em branco para não alterar',
    PASSWORD_PLACEHOLDER_CREATE: 'Senha inicial',
    CONFIRM_PASSWORD: 'Confirmar Senha',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Repita a senha',
  },
  BUTTONS: {
    ADD_PHONE: 'Adicionar Telefone',
    ADD_ADDRESS: 'Adicionar Endereço',
    RESEND_EMAIL: 'Reenviar Verificação de E-mail',
    RESET_PASSWORD: 'Forçar Redefinição de Senha',
    DELETE_USER: 'Excluir Usuário (Soft Delete)',
  },
};
