export const AUTH_TEXTS = {
  LOGIN_TITLE: 'Entrar',
  LOGIN_SUBTITLE: 'Digite suas credenciais para acessar a plataforma.',
  LOGIN_EMAIL_LABEL: 'E-mail',
  LOGIN_PASSWORD_LABEL: 'Senha',
  LOGIN_EMAIL_PLACEHOLDER: 'torcedor@email.com',
  LOGIN_PASSWORD_PLACEHOLDER: '••••••••',
  LOGIN_FORGOT_PASSWORD: 'Esqueceu a senha?',
  LOGIN_SUBMIT_BUTTON: 'Acessar Portal',
  LOGIN_NO_ACCOUNT: 'Não tem uma conta?',
  LOGIN_REGISTER_LINK: 'Cadastre-se',
  LOGIN_WELCOME_TEXT: 'Bem-vindo ao portal oficial. Acesso exclusivo para sócios, torcedores e administração.',

  REGISTER_TITLE: 'Cadastro de Torcedor',
  REGISTER_SUBTITLE: 'Preencha as informações abaixo para prosseguir.',
  REGISTER_BRANDING_TITLE: 'E.C. PELOTAS',
  REGISTER_STEP_1_TITLE: 'Dados Pessoais',
  REGISTER_STEP_2_TITLE: 'Contato',
  REGISTER_STEP_3_TITLE: 'Endereço',
  REGISTER_STEP_4_TITLE: 'Segurança',

  REGISTER_FIRST_NAME_LABEL: 'Nome',
  REGISTER_LAST_NAME_LABEL: 'Sobrenome',
  REGISTER_CPF_LABEL: 'CPF',
  REGISTER_BIRTH_DATE_LABEL: 'Data de Nascimento',
  REGISTER_EMAIL_LABEL: 'E-mail de Acesso',
  REGISTER_PHONE_LABEL: 'Telefone Principal',
  REGISTER_IS_WHATSAPP: 'Este número é WhatsApp',
  REGISTER_ZIP_CODE_LABEL: 'CEP',
  REGISTER_STREET_LABEL: 'Logradouro (Rua)',
  REGISTER_NUMBER_LABEL: 'Número',
  REGISTER_NEIGHBORHOOD_LABEL: 'Bairro',
  REGISTER_CITY_LABEL: 'Cidade',
  REGISTER_STATE_LABEL: 'Estado (UF)',
  REGISTER_PASSWORD_LABEL: 'Criar Senha',
  REGISTER_CONFIRM_PASSWORD_LABEL: 'Confirmar Senha',

  REGISTER_BUTTON_PREV: 'Voltar',
  REGISTER_BUTTON_NEXT: 'Próximo',
  REGISTER_BUTTON_SUBMIT: 'Finalizar Cadastro',
  REGISTER_ALREADY_HAVE_ACCOUNT: 'Já tem uma conta?',
  REGISTER_LOGIN_LINK: 'Faça login',

  REGISTER_SUCCESS_TITLE: 'Cadastro Concluído!',
  REGISTER_SUCCESS_SUBTITLE: 'Seja muito bem-vindo ao portal do Esporte Clube Pelotas.',
  REGISTER_SUCCESS_REDIRECTING: 'Redirecionando para o login...',

  VERIFY_EMAIL_HERO_TITLE: 'E.C. Pelotas',
  VERIFY_EMAIL_HERO_SUBTITLE: 'Estamos quase lá! Verifique sua identidade para liberar o seu acesso exclusivo.',
  VERIFY_EMAIL_TITLE: 'Verifique seu e-mail',
  VERIFY_EMAIL_SUBTITLE_PART_1: 'Enviamos um código de 6 dígitos para ',
  VERIFY_EMAIL_SUBTITLE_PART_2: '. Digite-o abaixo para confirmar.',
  VERIFY_EMAIL_CODE_LABEL: 'Código de Confirmação',
  VERIFY_EMAIL_CODE_PLACEHOLDER: '000000',
  VERIFY_EMAIL_SUBMIT_BUTTON: 'Confirmar Conta',
  VERIFY_EMAIL_NOT_RECEIVED: 'Não recebeu? ',
  VERIFY_EMAIL_RESEND_BUTTON: 'Reenviar código',
  VERIFY_EMAIL_RESENDING_BUTTON: 'Reenviando...',

  FORGOT_PASSWORD_HERO_TITLE: 'E.C. Pelotas',
  FORGOT_PASSWORD_HERO_SUBTITLE: 'Recupere o seu acesso de forma rápida e segura.',
  FORGOT_PASSWORD_SUCCESS_TITLE: 'E-mail Enviado!',
  FORGOT_PASSWORD_SUCCESS_SUBTITLE_1: 'Enviamos um link seguro de recuperação para o e-mail:',
  FORGOT_PASSWORD_SUCCESS_BACK_BUTTON: 'Voltar ao Login',
  FORGOT_PASSWORD_TITLE: 'Esqueci a Senha',
  FORGOT_PASSWORD_SUBTITLE: 'Informe seu CPF para recebermos um link de recuperação no seu e-mail cadastrado.',
  FORGOT_PASSWORD_CPF_LABEL: 'CPF',
  FORGOT_PASSWORD_CPF_PLACEHOLDER: '000.000.000-00',
  FORGOT_PASSWORD_SUBMIT_BUTTON: 'Enviar E-mail',

  RESET_PASSWORD_HERO_TITLE: 'E.C. Pelotas',
  RESET_PASSWORD_HERO_SUBTITLE: 'Sua conta protegida e em segurança.',
  RESET_PASSWORD_TITLE: 'Nova Senha',
  RESET_PASSWORD_SUBTITLE: 'Crie uma nova senha forte para acessar a sua conta.',
  RESET_PASSWORD_NEW_LABEL: 'Nova Senha',
  RESET_PASSWORD_NEW_PLACEHOLDER: '******',
  RESET_PASSWORD_CONFIRM_LABEL: 'Confirmar Nova Senha',
  RESET_PASSWORD_CONFIRM_PLACEHOLDER: '******',
  RESET_PASSWORD_SUBMIT_BUTTON: 'Redefinir Senha',
} as const;
