export const AUTH_TEXTS = {
  LOGIN_TITLE: 'Entrar',
  LOGIN_SUBTITLE: 'Digite suas credenciais para acessar a plataforma.',
  LOGIN_EMAIL_LABEL: 'E-mail',
  LOGIN_PASSWORD_LABEL: 'Senha',
  LOGIN_EMAIL_PLACEHOLDER: 'torcedor@email.com',
  LOGIN_PASSWORD_PLACEHOLDER: '••••••••',
  LOGIN_FORGOT_PASSWORD: 'Esqueceu a senha?',
  LOGIN_SUBMIT_BUTTON: 'Acessar Portal',
  LOGIN_NO_ACCOUNT: 'Não tem uma conta?',
  LOGIN_REGISTER_LINK: 'Cadastre-se',
  LOGIN_WELCOME_TEXT: 'Bem-vindo ao portal oficial. Acesso exclusivo para sócios, torcedores e administração.',

  REGISTER_TITLE: 'Cadastro de Torcedor',
  REGISTER_SUBTITLE: 'Preencha as informações abaixo para prosseguir.',
  REGISTER_BRANDING_TITLE: 'E.C. PELOTAS',
  REGISTER_STEP_1_TITLE: 'Dados Pessoais',
  REGISTER_STEP_2_TITLE: 'Contato',
  REGISTER_STEP_3_TITLE: 'Endereço',
  REGISTER_STEP_4_TITLE: 'Segurança',

  REGISTER_FIRST_NAME_LABEL: 'Nome',
  REGISTER_LAST_NAME_LABEL: 'Sobrenome',
  REGISTER_CPF_LABEL: 'CPF',
  REGISTER_BIRTH_DATE_LABEL: 'Data de Nascimento',
  REGISTER_EMAIL_LABEL: 'E-mail de Acesso',
  REGISTER_PHONE_LABEL: 'Telefone Principal',
  REGISTER_IS_WHATSAPP: 'Este número é WhatsApp',
  REGISTER_ZIP_CODE_LABEL: 'CEP',
  REGISTER_STREET_LABEL: 'Logradouro (Rua)',
  REGISTER_NUMBER_LABEL: 'Número',
  REGISTER_NEIGHBORHOOD_LABEL: 'Bairro',
  REGISTER_CITY_LABEL: 'Cidade',
  REGISTER_STATE_LABEL: 'Estado (UF)',
  REGISTER_PASSWORD_LABEL: 'Criar Senha',
  REGISTER_CONFIRM_PASSWORD_LABEL: 'Confirmar Senha',

  REGISTER_BUTTON_PREV: 'Voltar',
  REGISTER_BUTTON_NEXT: 'Próximo',
  REGISTER_BUTTON_SUBMIT: 'Finalizar Cadastro',
  REGISTER_ALREADY_HAVE_ACCOUNT: 'Já tem uma conta?',
  REGISTER_LOGIN_LINK: 'Faça login',

  REGISTER_SUCCESS_TITLE: 'Cadastro Concluído!',
  REGISTER_SUCCESS_SUBTITLE: 'Seja muito bem-vindo ao portal do Esporte Clube Pelotas.',
  REGISTER_SUCCESS_REDIRECTING: 'Redirecionando para o login...',
} as const;
