export const PROFILE_TEXTS = {
  // General Profile
  PAGE_TITLE: 'Meu Perfil',
  PAGE_SUBTITLE: 'Gerencie suas informações, segurança e preferências.',
  TAB_PERSONAL: 'Dados Pessoais',
  TAB_SECURITY: 'Segurança',
  TAB_ADDRESSES: 'Endereços',
  TAB_PREFERENCES: 'Preferências',

  // Personal Data Tab
  PERSONAL_TITLE: 'Dados Pessoais',
  PERSONAL_BUTTON_EDIT: 'Editar',
  PERSONAL_BUTTON_CANCEL: 'Cancelar',
  PERSONAL_BUTTON_SAVE: 'Salvar',
  PERSONAL_PHOTO_EDIT_TITLE: 'Editar foto',
  PERSONAL_PHOTO_DELETE_TITLE: 'Excluir foto',
  PERSONAL_PHOTO_ADD_TITLE: 'Adicionar foto',
  PERSONAL_LABEL_FIRST_NAME: 'Nome',
  PERSONAL_LABEL_LAST_NAME: 'Sobrenome',
  PERSONAL_LABEL_FULL_NAME: 'Nome Completo',
  PERSONAL_LABEL_CPF: 'CPF',
  PERSONAL_LABEL_BIRTH_DATE: 'Data de Nascimento',
  PERSONAL_LABEL_CREATED_AT: 'Criado em',
  PERSONAL_LABEL_UPDATED_AT: 'Atualizado em',
  PERSONAL_MODAL_DELETE_PHOTO_TITLE: 'Excluir Foto',
  PERSONAL_MODAL_DELETE_PHOTO_DESC: 'Tem certeza que deseja excluir sua foto de perfil? Esta ação não poderá ser desfeita.',
  PERSONAL_MODAL_DELETE_PHOTO_CONFIRM: 'Excluir Foto',
  PERSONAL_MODAL_DELETE_PHOTO_CANCEL: 'Manter Foto',
  PERSONAL_LOADING_SAVING: 'Salvando...',
  PERSONAL_LOADING_FETCHING: 'Carregando...',

  // Security Tab
  SECURITY_TITLE: 'Segurança e Acesso',
  SECURITY_DESCRIPTION: 'Proteja sua conta utilizando verificação em duas etapas para alterações sensíveis.',
  SECURITY_EMAIL_LABEL: 'E-mail Cadastrado',
  SECURITY_PHONE_LABEL: 'Celular Cadastrado',
  SECURITY_PASSWORD_LABEL: 'Senha de Acesso',
  SECURITY_PASSWORD_DESC: 'Atualize sua senha periodicamente para manter sua conta segura.',
  SECURITY_STATUS_VERIFIED: 'Verificado',
  SECURITY_STATUS_PENDING: 'Pendente',
  SECURITY_BUTTON_CHANGE_EMAIL: 'Alterar E-mail',
  SECURITY_BUTTON_VERIFY_EMAIL: 'Verificar E-mail',
  SECURITY_BUTTON_CHANGE_PHONE: 'Alterar Número',
  SECURITY_BUTTON_VERIFY_PHONE: 'Verificar Número',
  SECURITY_BUTTON_CHANGE_PASSWORD: 'Trocar Senha',
  SECURITY_DANGER_ZONE_TITLE: 'Zona de Risco',
  SECURITY_DANGER_ZONE_DESC: 'A exclusão da sua conta é imediata e irreversível. Todos os seus dados serão apagados.',
  SECURITY_BUTTON_DELETE_ACCOUNT: 'Excluir minha conta',
  SECURITY_PHONE_NOT_INFORMED: 'Não informado',

  // Addresses Tab
  ADDRESSES_TITLE: 'Meus Endereços',
  ADDRESSES_DESCRIPTION: 'Gerencie seus endereços para entrega de carteirinha e produtos.',
  ADDRESSES_ADD_BUTTON: 'Adicionar Endereço',
  ADDRESSES_BADGE_PRIMARY: 'Principal',
  ADDRESSES_BUTTON_EDIT: 'Editar',
  ADDRESSES_BUTTON_DELETE: 'Excluir',
  ADDRESSES_EMPTY_MESSAGE: 'Você ainda não possui nenhum endereço cadastrado.',
  ADDRESSES_ZIPCODE: 'CEP',
  ADDRESSES_NEIGHBORHOOD: 'Bairro',
  ADDRESSES_ADD_TITLE: 'Adicionar Endereço',
  ADDRESSES_EDIT_TITLE: 'Editar Endereço',
  ADDRESSES_FORM_STREET: 'Rua / Avenida',
  ADDRESSES_FORM_NUMBER: 'Número',
  ADDRESSES_FORM_COMPLEMENT: 'Complemento',
  ADDRESSES_FORM_CITY: 'Cidade',
  ADDRESSES_FORM_STATE: 'Estado',
  ADDRESSES_FORM_PRIMARY: 'Tornar como endereço principal',
  ADDRESSES_BUTTON_CANCEL: 'Cancelar',
  ADDRESSES_BUTTON_SAVE: 'Salvar Endereço',
  ADDRESSES_CONFIRM_DELETE: 'Tem certeza que deseja excluir este endereço?',

  // Preferences Tab
  PREFERENCES_TITLE: 'Preferências e Privacidade',
  PREFERENCES_DESCRIPTION: 'Gerencie suas configurações de comunicação e seus dados de acordo com a LGPD.',
  PREFERENCES_COMMS_TITLE: 'Comunicações',
  PREFERENCES_COMMS_EMAIL_LABEL: 'Novidades por E-mail',
  PREFERENCES_COMMS_EMAIL_DESC: 'Receba promoções exclusivas, notícias do clube e avisos sobre ingressos no seu e-mail.',
  PREFERENCES_COMMS_SMS_LABEL: 'Avisos por SMS',
  PREFERENCES_COMMS_SMS_DESC: 'Receba alertas importantes sobre seus planos e compras via mensagem de texto.',
  PREFERENCES_BUTTON_SAVE: 'Salvar Preferências',
  PREFERENCES_PRIVACY_TITLE: 'Privacidade (LGPD)',
  PREFERENCES_PRIVACY_DESC: 'Em conformidade com a Lei Geral de Proteção de Dados, você tem o direito de solicitar uma cópia de todos os dados que mantemos sobre você.',
  PREFERENCES_BUTTON_EXPORT: 'Exportar meus dados (JSON)',

  // Sensitive Action Modal
  SENSITIVE_MODAL_TITLE_DEFAULT: 'Confirmação de Segurança',
  SENSITIVE_MODAL_DESC_DEFAULT: 'Por motivos de segurança, digite sua senha atual para continuar com esta ação.',
  SENSITIVE_MODAL_PASSWORD_LABEL: 'Senha Atual',
  SENSITIVE_MODAL_PASSWORD_PLACEHOLDER: '••••••••',
  SENSITIVE_MODAL_BUTTON_CONFIRM: 'Confirmar',
  SENSITIVE_MODAL_BUTTON_CANCEL: 'Cancelar',

  // Delete Account Modal
  DELETE_ACCOUNT_MODAL_TITLE: 'Excluir Conta',
  DELETE_ACCOUNT_MODAL_DESC: 'Você está prestes a excluir sua conta. Esta ação é irreversível. Para confirmar, digite sua senha atual.',
  DELETE_ACCOUNT_MODAL_BUTTON_CONFIRM: 'Sim, excluir conta',

  // Crop Modal
  CROP_MODAL_TITLE: 'Ajustar Foto',
  CROP_MODAL_ZOOM: 'Zoom',
  CROP_MODAL_USE_ORIGINAL: 'Usar Original',
  CROP_MODAL_CANCEL: 'Cancelar',
  CROP_MODAL_SAVE: 'Salvar',

  // Changes Tab
  TAB_CHANGES: 'Pendências',
  CHANGES_TITLE: 'Alterações Pendentes',
  CHANGES_DESCRIPTION: 'Você possui solicitações de alteração aguardando confirmação de segurança.',
  CHANGES_EMPTY_TITLE: 'Tudo Certo!',
  CHANGES_EMPTY_DESC: 'Você não possui nenhuma solicitação de alteração pendente.',
  CHANGES_BADGE_WAITING: 'Aguardando Confirmação',
  CHANGES_CARD_TITLE_EMAIL: 'Alteração de E-mail',
  CHANGES_CARD_TITLE_PHONE: 'Alteração de Celular',
  CHANGES_CARD_NEW_EMAIL: 'Foi solicitada a alteração para:',
  CHANGES_CARD_NEW_PHONE: 'Foi solicitada a alteração para:',
  CHANGES_CARD_INSTRUCTIONS_EMAIL: 'Enviamos um código de 6 dígitos para o seu NOVO e-mail. Insira o código abaixo para confirmar a troca.',
  CHANGES_CARD_INSTRUCTIONS_PHONE: 'Enviamos um código de 6 dígitos para o seu NOVO celular. Insira o código abaixo para confirmar a troca.',
  CHANGES_INPUT_CODE_LABEL: 'Código de Confirmação (OTP)',
  CHANGES_INPUT_CODE_PLACEHOLDER: 'Ex: 123456',
  CHANGES_BUTTON_CONFIRM: 'Confirmar Alteração',

  // Change Contact Drawer
  CHANGE_EMAIL_DRAWER_TITLE: 'Alterar E-mail',
  CHANGE_PHONE_DRAWER_TITLE: 'Alterar Celular',
  CHANGE_EMAIL_LABEL: 'Novo E-mail',
  CHANGE_PHONE_LABEL: 'Novo Celular',
  CHANGE_EMAIL_PLACEHOLDER: 'Digite o novo e-mail',
  CHANGE_PHONE_PLACEHOLDER: 'Digite o novo celular',
  CHANGE_PHONE_INFO_WARNING: 'O código de confirmação para esta alteração será enviado temporariamente para o seu e-mail cadastrado.',
  CHANGE_CURRENT_PASSWORD_LABEL: 'Sua Senha Atual',
  CHANGE_CURRENT_PASSWORD_PLACEHOLDER: 'Para confirmar sua identidade',
  CHANGE_BUTTON_REQUEST: 'Solicitar',

  // Change Password Drawer
  CHANGE_PASSWORD_DRAWER_TITLE: 'Alterar Senha',
  CHANGE_PASSWORD_LABEL_CURRENT: 'Senha Atual',
  CHANGE_PASSWORD_LABEL_NEW: 'Nova Senha',
  CHANGE_PASSWORD_LABEL_CONFIRM: 'Confirme a Nova Senha',
  CHANGE_PASSWORD_ERROR_MISMATCH: 'A nova senha e a confirmação não conferem.',
  CHANGE_PASSWORD_ERROR_MIN_LENGTH: 'A nova senha deve ter pelo menos 6 caracteres.',
  CHANGE_PASSWORD_BUTTON_SAVE: 'Salvar',

  // Toast messages
  TOAST_REQUEST_CHANGE_SUCCESS: 'Solicitação enviada! Verifique a aba de Pendências.',
  TOAST_REQUEST_CHANGE_ERROR: 'Falha ao solicitar alteração.',
  TOAST_CONFIRM_CHANGE_EMAIL_SUCCESS: 'E-mail atualizado com sucesso!',
  TOAST_CONFIRM_CHANGE_PHONE_SUCCESS: 'Celular atualizado com sucesso!',
  TOAST_CONFIRM_CHANGE_ERROR: 'Falha ao confirmar alteração.',
  TOAST_CONFIRM_CHANGE_REQUIRED: 'Preencha o código de confirmação.',
  TOAST_UPDATE_PASSWORD_SUCCESS: 'Senha alterada com sucesso!',
  TOAST_UPDATE_PASSWORD_ERROR: 'Falha ao alterar senha.',
};
