export const SETTINGS_TEXTS = {
  TITLE: 'Configurações',
  SUBTITLE: 'Gerencie as configurações gerais e a aparência da plataforma.',
  TAB_GENERAL: 'Geral',
  TAB_THEME: 'Temas (Aparência)',
  GENERAL_DESC: 'Configurações gerais do sistema em breve.',
  THEME_DESC: 'Configuração de cores e modos (Claro/Escuro) em breve.',
  THEMES: {
    LOADING: 'Carregando temas...',
    LIST_DESC: 'Gerencie as paletas de cores do sistema. Apenas um tema pode estar ativo por vez.',
    NEW_THEME_BUTTON: 'Criar Novo Tema',
    TABLE_COL_NAME: 'Nome do Tema',
    TABLE_COL_STATUS: 'Status',
    TABLE_COL_COLORS: 'Cores (Primary / Background)',
    TABLE_COL_ACTIONS: 'Ações',
    BADGE_ACTIVE: 'Ativo',
    BADGE_INACTIVE: 'Inativo',
    BADGE_DEFAULT: 'Tema Padrão do Sistema',
    BTN_ACTIVATE: 'Ativar',
    BTN_EDIT: 'Editar',
    BTN_DELETE: 'Excluir',
    BTN_CANCEL: 'Cancelar',
    BTN_SAVE: 'Salvar Alterações',
    BTN_CREATE: 'Criar Tema',
    BTN_PREVIEW: 'Visualizar',
    EMPTY_LIST: 'Nenhum tema encontrado.',
    PREVIEW_EMPTY_STATE: 'Selecione um tema na tabela para visualizar o preview.',
    PREVIEW_PANEL_TITLE: 'Visualização: ',
    PREVIEW_PANEL_BTN_CANCEL: 'Cancelar',
    PREVIEW_PANEL_BTN_MAIN: 'Ação Principal',
    DRAWER_TITLE_EDIT: 'Editar Tema',
    DRAWER_TITLE_NEW: 'Novo Tema',
    FIELD_NAME_LABEL: 'Nome do Tema',
    FIELD_NAME_PLACEHOLDER: 'Ex: Outubro Rosa',
    PALETTE_LIGHT: 'Paleta Modo Claro',
    PALETTE_DARK: 'Paleta Modo Escuro',
    COLOR_PRIMARY: 'Cor do Botão Primário (Primary)',
    COLOR_SECONDARY: 'Cor de Destaque Secundário (Secondary)',
    COLOR_BUTTON_SECONDARY: 'Cor do Botão Secundário',
    COLOR_BACKGROUND: 'Fundo Geral do Site (Background)',
    COLOR_SURFACE: 'Fundo Base (Surface)',
    COLOR_HEADER: 'Fundo do Cabeçalho (Header)',
    COLOR_CARD: 'Fundo dos Cards (Cards)',
    COLOR_DRAWER: 'Fundo de Paineis Laterais e Modais (Drawer)',
    COLOR_TABLE: 'Fundo de Tabelas (Table)',
    COLOR_TEXT_PRIMARY: 'Texto Principal',
    COLOR_TEXT_SECONDARY: 'Texto Secundário',
    COLOR_BORDER: 'Bordas',
    DELETE_TITLE: 'Excluir Tema',
    DELETE_MESSAGE: 'Tem certeza que deseja excluir o tema "{themeName}"? Esta ação não pode ser desfeita.',
    DELETE_CONFIRM: 'Sim, excluir',
    SUCCESS_ACTIVATE: 'Tema ativado com sucesso! Recarregando cores...',
    ERROR_ACTIVATE: 'Erro ao ativar tema.',
    ERROR_FETCH: 'Erro ao buscar temas.',
    ERROR_SAVE: 'Erro ao salvar o tema.',
    ERROR_DELETE: 'Erro ao remover tema.',
    SUCCESS_SAVE: 'Tema salvo com sucesso!',
    SUCCESS_DELETE: 'Tema removido com sucesso!',
    VALIDATION_NAME: 'O nome do tema é obrigatório.',
  }
};
